a=input("Combien d'heures se sont ecoulées? ")
b=input("Combien de minutes se sont écoulées? ")
c=input("Combien de secondes se sont écoulées? ")
a=int(a)
b=int(b)
c=int(c)
a1=(a*3600)
b1=(b*60)
c11=(c*1)
print((c11)+(b1)+(a1))