a=input("Combien d'heures se sont ecoulées? ")
b=input("Combien de minutes se sont écoulées? ")
c=input("Combien de secondes se sont écoulées? ")
a=int(a)
b=int(b)
c=int(c)
a1=(a*1200)
b1=(b*60)
c1=(c*1)
print(a1+b1+c1)
